### ISSUE TITLE
Добавить картинку к Наименованию

### ISSUE THREAD

**Issue by vic7920** [modulbank-pay/modulbank-opencart2.0#2]
Салют!
Пользовался прошлой версией модуля и как то получалось отображать такое https://clip2net.com/s/4afMbkd
вот эта строчка, в каком-то коде была, помню что сам её куда-то вставлял: 'Оплата сейчас по карте вашего банка < img src="/image/pay/vmm.png" >'

Вчера переустановил, из-за появляющихся ошибок, версию новую модуля, и теперь никак не могу найти файл, где эта строчка была написана, командером проискал всё, и так ничего и не обнаружил...
а в настройках модуля оплаты только внести можно словесное название, которое оно выводит на экран для пользователей.

Если кто знает, где копать - черканите пожалуйста какой файл поправить, 
хочется не вот такое безликое https://c2n.me/4afMDoy
а более информативное для своих клиентов.

**Comment by VampiRUS** [comment]
catalog/model/payment/modulbank.php
`'title'      => $this->config->get('modulbank_paymentname'),`
